version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - finance_network

  api:
    build: .
    command: uvicorn orchestrator.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - finance_network

  streamlit:
    build: .
    command: streamlit run streamlit_app/app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  redis_data:
